"""add difficulty to problems

Revision ID: 0329cade6a93
Revises: 6e6d74dfc149
Create Date: 2026-06-26 10:28:01.110165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0329cade6a93'
down_revision: Union[str, Sequence[str], None] = '6e6d74dfc149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('difficulty', sa.String(), server_default='Medium', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'difficulty')
    # ### end Alembic commands ###
