"""add log_s3_key to interview_sessions

Revision ID: 0d829aefd2de
Revises: 47f05fe52f5d
Create Date: 2026-07-07 14:00:13.488117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d829aefd2de'
down_revision: Union[str, Sequence[str], None] = '47f05fe52f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('log_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'log_s3_key')
    # ### end Alembic commands ###
