"""add codebase_path to interview_sessions

Revision ID: 60f04a034e54
Revises: 8f4e2c1a9b3d
Create Date: 2026-07-05 17:10:37.273370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f04a034e54'
down_revision: Union[str, Sequence[str], None] = '8f4e2c1a9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('codebase_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'codebase_path')
    # ### end Alembic commands ###
