"""add_interview_scoring_status

Revision ID: 6e6d74dfc149
Revises: 1b4429f9f464
Create Date: 2026-06-25 23:31:56.702216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6d74dfc149'
down_revision: Union[str, Sequence[str], None] = '1b4429f9f464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires a default for NOT NULL columns added to existing tables.
    op.add_column(
        'interviews',
        sa.Column('scoring_status', sa.String(), nullable=False, server_default='not_scored'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'scoring_status')
    # ### end Alembic commands ###
